{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: grafana
spec:
  replicas: {{ .Values.grafana.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
    spec:
      serviceAccountName: {{ .Values.grafana.serviceAccountName }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.grafana.service.port }}
              protocol: TCP
          envs:
            {{- toYaml .Values.grafana.envs | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.grafana.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.grafana.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.grafana.resources | nindent 12 }}
          {{- with .Values.grafana.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.grafana.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}