{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
spec:
  replicas: {{ .Values.prometheus.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus
    spec:
      serviceAccountName: {{ .Values.prometheus.serviceAccountName }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.prometheus.image.pullPolicy }}
          args:
            - --config.file=/configs/prometheus.yaml
            - --web.enable-remote-write-receiver
            - --enable-feature=exemplar-storage
          ports:
            - name: http
              containerPort: {{ .Values.prometheus.service.port }}
              protocol: TCP
          envs:
            {{- toYaml .Values.prometheus.envs | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.prometheus.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.prometheus.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.prometheus.resources | nindent 12 }}
          {{- with .Values.prometheus.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.prometheus.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}