{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: tempo
  labels:
    app.kubernetes.io/name: tempo
spec:
  type: {{ .Values.tempo.service.type }}
  ports:
    - port: {{ .Values.tempo.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 3200
      targetPort: 3200
      protocol: TCP
      name: tempo
    - port: 4317
      targetPort: 4317
      protocol: TCP
      name: grpc
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http-80
  selector:
    app.kubernetes.io/name: tempo
{{- end }}