{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app.kubernetes.io/name: otelCollector
spec:
  type: {{ .Values.otelCollector.service.type }}
  ports:
    - port: {{ .Values.otelCollector.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 4317
      targetPort: 4317
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: otelCollector
{{- end }}